kind: Deployment
apiVersion: apps/v1
metadata:
  name: feedback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - name: feedback
          image: shalitha98/feedback:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
